In [1]:
import pandas as pd
import openpyxl

In [3]:
excel = pd.read_excel("C:/Users/moise/OneDrive/Documentos/UPY/project/Estancia ENES/Scraper_and_mapping/Databases/DD12487_EH.xlsx", engine="openpyxl", index_col=0)
excel

,pk_mes,ngasto_d01,ngasto_d02,ngasto_d03,ngasto_d04,ngasto_d05,ngasto_d06,ngasto_d07,ngasto_d08,ngasto_d09,...,ngasto_d22,ngasto_d23,ngasto_d24,ngasto_d25,ngasto_d26,ngasto_d27,ngasto_d28,ngasto_d29,ngasto_d30,ngasto_d31
pk_anio,,,,,,,,,,,,,,,,,,,,,
1954.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.042,0.032,0.032,0.046,0.062,0.064
1954.0,6.0,0.029,0.029,0.056,0.052,0.030,0.029,3.112,0.699,0.310,...,0.734,9.423,5.058,0.626,4.752,0.841,1.365,1.676,3.658,NaN
1954.0,7.0,0.748,0.339,0.346,2.245,2.060,1.884,11.406,2.418,14.415,...,2.706,4.901,8.283,2.540,1.340,0.891,0.900,2.382,8.913,14.505
1954.0,8.0,4.905,5.025,3.417,2.013,2.927,3.775,3.304,1.268,1.048,...,1.170,3.268,1.515,0.902,0.841,1.426,2.400,1.168,1.777,1.484
1954.0,9.0,0.971,0.685,0.620,0.524,0.734,0.629,0.477,0.279,0.222,...,0.272,0.448,0.719,1.121,0.430,0.339,0.263,0.259,0.263,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,**Calidad agua sí lo están haciendo.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,**SIMIT,NaN,NaN,NaN,**,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,**Ver Redes piezómetricas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = excel.iloc[:-7]
df

,pk_mes,ngasto_d01,ngasto_d02,ngasto_d03,ngasto_d04,ngasto_d05,ngasto_d06,ngasto_d07,ngasto_d08,ngasto_d09,...,ngasto_d22,ngasto_d23,ngasto_d24,ngasto_d25,ngasto_d26,ngasto_d27,ngasto_d28,ngasto_d29,ngasto_d30,ngasto_d31
pk_anio,,,,,,,,,,,,,,,,,,,,,
1954.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.04200,0.03200,0.03200,0.04600,0.06200,0.06400
1954.0,6.0,0.02900,0.029,0.05600,0.05200,0.03000,0.029,3.11200,0.69900,0.31000,...,0.73400,9.42300,5.05800,0.62600,4.75200,0.84100,1.36500,1.67600,3.65800,NaN
1954.0,7.0,0.74800,0.339,0.34600,2.24500,2.06000,1.884,11.40600,2.41800,14.41500,...,2.70600,4.90100,8.28300,2.54000,1.34000,0.89100,0.90000,2.38200,8.91300,14.50500
1954.0,8.0,4.90500,5.025,3.41700,2.01300,2.92700,3.775,3.30400,1.26800,1.04800,...,1.17000,3.26800,1.51500,0.90200,0.84100,1.42600,2.40000,1.16800,1.77700,1.48400
1954.0,9.0,0.97100,0.685,0.62000,0.52400,0.73400,0.629,0.47700,0.27900,0.22200,...,0.27200,0.44800,0.71900,1.12100,0.43000,0.33900,0.26300,0.25900,0.26300,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006.0,8.0,0.93329,7.53106,13.98172,11.58793,29.74412,31.16605,10.09836,11.90856,4.98806,...,7.44804,6.42355,18.50207,26.84380,36.86395,49.29681,27.44371,15.04874,9.49386,7.64956
2006.0,9.0,6.53157,15.22901,9.24618,3.65244,2.61822,8.60887,41.13563,21.19259,9.33847,...,10.22158,6.27294,20.10095,20.83191,10.13239,8.18113,7.70919,6.83877,8.72564,NaN
2006.0,10.0,17.24038,13.22681,8.82262,6.92526,4.83819,2.21671,1.89170,1.84702,1.72673,...,3.58602,44.89520,36.73314,27.70230,19.04898,9.13219,7.43538,6.47196,5.53748,2.76246
2006.0,11.0,2.45398,1.9417,1.85383,1.69802,1.60353,1.43801,1.34404,1.19537,1.15683,...,0.66136,0.61826,0.61207,0.59052,0.58800,0.56900,0.52780,0.52600,0.52600,NaN
2006.0,12.0,0.52600,0.52057,0.50191,0.48758,0.43804,0.423,0.42300,0.42300,0.45316,...,0.42300,0.42300,0.42300,0.42300,0.42300,0.42300,0.42300,0.31817,0.12700,0.12700

In [5]:
excel_df = excel.T

In [6]:
excel_df = excel_df.iloc[:, :-7]  # Elimina las últimas 7 columnas

In [7]:
excel_df.to_excel("C:/Users/moise/OneDrive/Documentos/UPY/project/Estancia ENES/Scraper_and_mapping/Databases/DD12487_EH_tran.xlsx", index=True, engine="openpyxl")

In [8]:
excel_df

pk_anio,1954.0,1954.0,1954.0,1954.0,1954.0,1954.0,1954.0,1954.0,1955.0,1955.0,...,2006.0,2006.0,2006.0,2006.0,2006.0,2006.0,2006.0,2006.0,2006.0,2006.0
pk_mes,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,1.0,2.0,...,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0
ngasto_d01,NaN,0.029,0.748,4.905,0.971,0.731,0.116,0.044,0.044,0.038,...,0.04097,0.022,0.01302,0.01419,0.043,0.93329,6.53157,17.24038,2.45398,0.526
ngasto_d02,NaN,0.029,0.339,5.025,0.685,0.398,0.116,0.044,0.048,0.04,...,0.041,0.022,0.013,0.013,0.043,7.53106,15.22901,13.22681,1.9417,0.52057
ngasto_d03,NaN,0.056,0.346,3.417,0.62,0.356,0.116,0.044,0.05,0.04,...,0.041,0.01761,0.013,0.02873,0.043,13.98172,9.24618,8.82262,1.85383,0.50191
ngasto_d04,NaN,0.052,2.245,2.013,0.524,0.288,0.084,0.04,0.05,0.048,...,0.041,0.01407,0.013,0.05145,0.043,11.58793,3.65244,6.92526,1.69802,0.48758
ngasto_d05,NaN,0.03,2.06,2.927,0.734,0.699,0.088,0.05,0.05,0.052,...,0.041,0.014,0.013,0.05028,0.043,29.74412,2.61822,4.83819,1.60353,0.43804
ngasto_d06,NaN,0.029,1.884,3.775,0.629,0.69,0.093,0.048,0.052,0.05,...,0.041,0.014,0.013,0.04392,0.05473,31.16605,8.60887,2.21671,1.43801,0.423
ngasto_d07,NaN,3.112,11.406,3.304,0.477,0.4,0.06,0.046,0.052,0.048,...,0.041,0.014,0.013,0.042,0.21049,10.09836,41.13563,1.8917,1.34404,0.423
ngasto_d08,NaN,0.699,2.418,1.268,0.279,0.298,0.076,0.046,0.05,0.048,...,0.041,0.014,0.01219,0.03118,0.13068,11.90856,21.19259,1.84702,1.19537,0.423
ngasto_d09,NaN,0.31,14.415,1.048,0.222,0.259,0.042,0.046,0.052,0.042,...,0.041,0.014,0.01,0.02135,0.05647,4.98806,9.33847,1.72673,1.15683,0.45316
ngasto_d10,NaN,0.327,11.569,1.204,0.221,0.259,0.042,0.04,0.052,0.027,...,0.041,0.014,0.01,0.021,0.052,1.78116,24.86402,1.38945,1.1204,0.52059
ngasto_d11,NaN,2.453,4.139,1.06,0.208,0.468,0.044,0.044,0.052,0.026,...,0.041,0.014,0.01,0.0174,0.052,5.13301,25.43895,1.35696,1.02288,0.49959
ngasto_d12,NaN,10.447,1.497,1.125,0.184,3.359,0.046,0.046,0.05,0.026,...,0.041,0.014,0.01,0.01317,0.052,4.07774,26.95304,1.97522,1.00734,0.497
ngasto_d13,NaN,32.709,0.971,3.173,0.125,0.76,0.046,0.046,0.05,0.026,...,0.041,0.014,0.01,0.01678,0.052,19.27057,11.89584,5.50599,0.98291,0.48162
ngasto_d14,NaN,7.049,0.75,1.781,0.109,7.212,0.046,0.046,0.05,0.026,...,0.041,0.014,0.01,0.02233,6.62969,7.79235,8.35754,2.48572,0.95841,0.42606
ngasto_d15,NaN,1.472,1.728,0.8,0.113,1.643,0.052,0.048,0.05,0.026,...,0.041,0.014,0.01,0.02586,2.09825,6.78889,7.60828,2.69674,0.88522,0.423
ngasto_d16,NaN,1.551,2.114,0.922,0.12,0.678,0.056,0.044,0.05,0.025,...,0.041,0.014,0.01,0.03076,0.34513,27.61936,7.36736,6.15869,0.85466,0.423
ngasto_d17,NaN,4.002,1.499,3.063,0.112,0.358,0.054,0.044,0.052,0.025,...,0.0307,0.014,0.01,0.03108,0.31199,8.07587,7.94105,5.18951,0.80205,0.423
ngasto_d18,NaN,1.07,0.966,8.514,0.104,0.31,0.05,0.04,0.052,0.025,...,0.02227,0.014,0.01,0.01,0.30341,6.78814,7.68145,2.30623,0.70815,0.423
ngasto_d19,NaN,0.439,4.205,3.118,0.104,0.245,0.05,0.038,0.052,0.025,...,0.022,0.014,0.01,0.01,0.21637,9.08276,10.46442,1.78798,0.69606,0.423
ngasto_d20,NaN,0.435,5.15,2.346,0.126,0.179,0.05,0.042,0.052,0.025,...,0.022,0.014,0.01,0.01575,0.13319,10.77844,7.45151,1.42893,0.67956,0.423
ngasto_d21,NaN,0.381,9.17,1.534,0.15,0.174,0.05,0.038,0.052,0.025,...,0.022,0.014,0.01,0.07967,0.06395,12.62436,7.07329,1.40496,0.679,0.423
ngasto_d22,NaN,0.734,2.706,1.17,0.272,0.158,0.048,0.038,0.052,0.025,...,0.022,0.014,0.01,0.13804,0.17704,7.44804,10.22158,3.58602,0.66136,0.423
ngasto_d23,NaN,9.423,4.901,3.268,0.448,0.163,0.048,0.038,0.052,0.026,...,0.022,0.014,0.01,0.043,0.05588,6.42355,6.27294,44.8952,0.61826,0.423
ngasto_d24,NaN,5.058,8.283,1.515,0.719,0.256,0.058,0.038,0.05,0.026,...,0.022,0.014,0.01,0.043,0.036,18.50207,20.10095,36.73314,0.61207,0.423
ngasto_d25,NaN,0.626,2.54,0.902,1.121,0.865,0.054,0.042,0.048,0.026,...,0.022,0.014,0.01,0.043,0.036,26.8438,20.83191,27.7023,0.59052,0.423
ngasto_d26,0.042,4.752,1.34,0.841,0.43,0.225,0.058,0.04,0.05,0.026,...,0.022,0.014,0.01,0.043,0.51611,36.86395,10.13239,19.04898,0.588,0.423
ngasto_d27,0.032,0.841,0.891,1.426,0.339,0.219,0.056,0.038,0.05,0.025,...,0.022,0.014,0.01,0.29081,7.49491,49.29681,8.18113,9.13219,0.569,0.423
ngasto_d28,0.032,1.365,0.9,2.4,0.263,0.179,0.056,0.038,0.05,0.025,...,0.022,0.014,0.02223,0.07668,5.73654,27.44371,7.70919,7.43538,0.5278,0.423
ngasto_d29,0.046,1.676,2.382,1.168,0.259,0.179,0.054,0.036,0.052,NaN,...,0.022,0.014,0.23005,0.043,8.58721,15.04874,6.83877,6.47196,0.526,0.31817
ngasto_d30,0.062,3.658,8.913,1.777,0.263,0.179,0.056,0.04,0.054,NaN,...,0.022,0.014,0.12848,0.043,8.54663,9.49386,8.72564,5.53748,0.526,0.127
ngasto_d31,0.064,NaN,14.505,1.484,NaN,0.179,NaN,0.034,0.052,NaN,...,0.022,NaN,0.03875,NaN,4.20272,7.64956,NaN,2.76246,NaN,0.127

In [ ]:
import pandas as pd

# Si 'pk_anio' está como índice, lo convertimos en columna
if 'level_0' in df.columns:
    df = df.drop(columns=['level_0'])
df.reset_index(inplace=True)

# Lista de nombres de meses
nombres_meses = ["ene.", "feb.", "mar.", "abr.", "may.", "jun.", "jul.", "ago.", "sep.", "oct.", "nov.", "dic."]

# Transformar el DataFrame de formato ancho a largo
df_long = df.melt(id_vars=["pk_anio", "pk_mes"], var_name="dia", value_name="valor")

# Extraer solo los números de día (ngasto_d01 → 1), ignorando los NaN
df_long["dia"] = df_long["dia"].str.extract(r"(\d+)")

# **Manejamos los NaN antes de convertir a int**
df_long = df_long.dropna(subset=["dia"])
df_long["dia"] = df_long["dia"].astype(int)

# **Convertimos 'pk_mes' y 'pk_anio' a int**
df_long["pk_mes"] = df_long["pk_mes"].astype(int)
df_long["pk_anio"] = df_long["pk_anio"].astype(int)

# Filtrar para eliminar el año 1954
df_long = df_long[df_long["pk_anio"] != 1954]

# Crear la columna "Fecha" en formato '1-ene.', '2-ene.', etc.
df_long["Fecha"] = df_long["dia"].astype(str) + "-" + df_long["pk_mes"].apply(lambda x: nombres_meses[x-1])

# Reorganizar el DataFrame para que los años sean columnas y las fechas sean el índice
df_pivot = df_long.pivot(index="Fecha", columns="pk_anio", values="valor")

# Asegurar que solo haya 365 filas y estén en orden correcto
fechas_ordenadas = [f"{d+1}-{m}" for m in nombres_meses for d in range(31) if not (m == "feb." and d >= 28)]  # Evita 29-feb.
df_pivot = df_pivot.reindex(fechas_ordenadas)

# Hacer que 'Fecha' sea el índice
df_pivot.index.name = "Fecha"

# Eliminar 'pk_anio' del encabezado
df_pivot.columns.name = None

# Mostrar el DataFrame transformado
df_pivot

In [ ]:
# Guardar el DataFrame en un archivo Excel
#df_pivot.to_excel("datos_transformados.xlsx")